### ISSUE TITLE
How can I add table attributes?

### ISSUE THREAD

**Issue by insign** [donquixote/cellbrush#8]
I saw in the code that is possible but looks not implemented....

I can do a PR, but, is this project active (or at least the PR will be analysed)?

**Comment by donquixote** [comment]
Hi,
see https://github.com/donquixote/cellbrush/pull/7

> is this project active

I spend time on projects like this every few months or once a year or so, depending if I have time.

The problem is not the time itself, but how I split my attention. It always takes me some time when I look at a project I have not touched for a while, until my brain is back on track.

And I often hesitate with new features because once a feature is added, I have to backward-support it.

**Comment by insign** [comment]
Add any attribute should use same way of functions like AddRowClass(), indeed, it must be replaced by something like AddAttr()

Miss this function is annoying...

Thanks anyway. Great class.

**Comment by donquixote** [comment]
Fixed!
@makoru-hikage 
I cherry-picked your commit and added a test.
